# Generated by Django 4.1.5 on 2023-01-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0012_guest_user_reservation_accept_reservation_reject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
