# Generated by Django 4.1.5 on 2023-01-30 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0015_alter_guest_phone_alter_guest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='first_name',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='firstname'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='last_name',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='lastname'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(blank=True, default='+11234567890', max_length=12, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='phone'),
        ),
    ]
