# Generated by Django 4.1.5 on 2023-01-30 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0017_alter_guest_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='phone'),
        ),
    ]
