# Generated by Django 4.1.5 on 2023-01-30 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0018_alter_guest_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='guest.guest'),
        ),
    ]
