# Generated by Django 4.1.5 on 2023-01-30 17:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0020_alter_guest_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(blank=True, default='+11234567890', max_length=12, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.guest'),
        ),
    ]
