# Generated by Django 4.1.5 on 2023-01-30 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0022_alter_guest_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(blank=True, default='+11234567890', max_length=12, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='phone'),
        ),
    ]
